# workflow name
name: actions single


on: [push, repository_dispatch]

# YQ_TOKEN
# YUQUE_GIT_HEXO
jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: "14.x"

      #安装依赖(包含yuque-hexo，此处无需安装) from https://github.com/x-cold/yuque-hexo
      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install yuque-hexo -g
          npm install

      # 此处请勿使用hexo clean&&yuque-hexo（重新构建时无需此命令行）同步语雀文章
      - name: yuque-hexo sync
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN_HEXO_SYNC_GITHUB_ONLINE}} # from: 这里是YUQUE_TOKEN: $不能随意改
        run: |
          hexo clean
          yuque-hexo sync || yuque-hexo sync || yuque-hexo sync  # 用 || 来重试的次数

      # 生成可访问的文档
      - name: hexo generate
        run: |
          hexo g
      
      - name: 设置Git信息
        run: |
          git config --global user.name 'yxlr123' 
          git config --global user.email 'dbh2858304517@gmail.com'      
      - name: 部署到Github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: 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
          repository-name: yxlr123/yxlr123.github.io
          branch: blog
          folder: public
          commit-message: '${{ github.event.head_commit.message }} Updated By Github Actions'
